global:
  scrape_interval: ${PROMETHEUS_SCRAPE_INTERVAL:-15s}
  evaluation_interval: ${PROMETHEUS_EVALUATION_INTERVAL:-15s}

scrape_configs:
  - job_name: 'fastapi'
    static_configs:
      - targets: ['backend:8000']
    metrics_path: '/metrics'
    scrape_interval: ${PROMETHEUS_SCRAPE_INTERVAL:-15s}
    scrape_timeout: 10s
